version: '3.1'
services:
  postgres:
    image: postgres:12
    container_name: pg_admin
    env_file: 
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    networks:
      - busify-network
    volumes:
      - postgres_data:${PGDATA}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD} --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - busify-test-network
  # redis-stack:
  #   image: redis/redis-stack:latest
  #   container_name: redis-stack
  #   ports:
  #     - '6379:6379'
  #     - '8001:8001'
  #   environment:
  #     REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --loglevel warning"
  #   networks:
  #     - busify-network

networks:
  busify-network:
    driver: bridge

volumes:
  postgres_data:
  # redis_data: